// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0OCdBQdL2sKpZ3KET0y5TMV3ht5aaxgs',
    appId: '1:571631180991:web:b88d73f60e85d3e49d7a0a',
    messagingSenderId: '571631180991',
    projectId: 'bilions-pos',
    authDomain: 'bilions-pos.firebaseapp.com',
    databaseURL: 'https://bilions-pos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bilions-pos.appspot.com',
    measurementId: 'G-5GP5GL5XCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFF0b6BIjSpit8Zx-wLbUKCLNRkAkOXQ',
    appId: '1:571631180991:android:c5c1de8c33e6b4059d7a0a',
    messagingSenderId: '571631180991',
    projectId: 'bilions-pos',
    databaseURL: 'https://bilions-pos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bilions-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFIkPE_0SCMq8FH6Kne0wAxtDvbQP2FSs',
    appId: '1:571631180991:ios:c6200a70c59e51219d7a0a',
    messagingSenderId: '571631180991',
    projectId: 'bilions-pos',
    databaseURL: 'https://bilions-pos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bilions-pos.appspot.com',
    androidClientId: '571631180991-n515f142slu0453l1pjovpqarrlplaqg.apps.googleusercontent.com',
    iosClientId: '571631180991-k2vqp1893p3llagbfscnemnvgpejcp7t.apps.googleusercontent.com',
    iosBundleId: 'org.bilions.manaw',
  );
}
